# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

select_yvine_cpp <- function(data, family_set, par_method, nonpar_method, mult, selcrit, weights, psi0, preselect_families, cores, var_types) {
    .Call(`_bivinereg_select_yvine_cpp`, data, family_set, par_method, nonpar_method, mult, selcrit, weights, psi0, preselect_families, cores, var_types)
}

cond_m_dist_cpp <- function(u, vinecop_r, margin, num_threads) {
    .Call(`_bivinereg_cond_m_dist_cpp`, u, vinecop_r, margin, num_threads)
}

cond_m2_dist_cpp <- function(u, vinecop_r, margin, num_threads) {
    .Call(`_bivinereg_cond_m2_dist_cpp`, u, vinecop_r, margin, num_threads)
}

cond_bi_dens_cpp <- function(u, vinecop_r, num_threads) {
    .Call(`_bivinereg_cond_bi_dens_cpp`, u, vinecop_r, num_threads)
}

cond_m_dens_cpp <- function(u, vinecop_r, margin, num_threads) {
    .Call(`_bivinereg_cond_m_dens_cpp`, u, vinecop_r, margin, num_threads)
}

